name: Publish release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      issues: write
      discussions: write
      pull-requests: write
      contents: write
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: release
        id: release
        run: make semantic-release-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}